"""Add lot 11 models

Revision ID: 1bcdb90a6d86
Revises: 1a630aeef438
Create Date: 2026-07-19 16:47:41.829591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcdb90a6d86'
down_revision: Union[str, Sequence[str], None] = '1a630aeef438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_uri', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_history_id'), ['id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_quality', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scrape_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('last_scrape_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('low_quality')

    with op.batch_alter_table('version_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_history_id'))

    op.drop_table('version_history')
    # ### end Alembic commands ###
