"""add extraction_nlp table

Revision ID: 2262aaa7b8c9
Revises: 799a3ffdf3cc
Create Date: 2026-07-12 15:18:12.484323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2262aaa7b8c9'
down_revision: Union[str, Sequence[str], None] = '799a3ffdf3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions_nlp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extractions_nlp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extractions_nlp_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extractions_nlp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extractions_nlp_id'))

    op.drop_table('extractions_nlp')
    # ### end Alembic commands ###
