"""initial schema

Revision ID: 799a3ffdf3cc
Revises: 
Create Date: 2026-07-12 14:36:34.000081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799a3ffdf3cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('inferred_type', sa.Enum('Avis', 'CPS', 'RC', 'Engagement', 'Formulaire', 'Inconnu', name='doctype'), nullable=True),
    sa.Column('status', sa.Enum('raw_zip', 'extracted', 'ocr_processed', 'failed', name='docstatus'), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('marches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_source_id', sa.Integer(), nullable=True),
    sa.Column('numero_appel_offre', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('titre_projet', sa.Text(), nullable=False),
    sa.Column('organisme_acheteur', sa.String(length=255), nullable=False),
    sa.Column('categorie_prestation', sa.Enum('Travaux', 'Fournitures', 'Services', 'Etudes', name='categoriemarche'), nullable=True),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_estimatif_mad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('caution_provisoire_mad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('caution_definitive_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('delai_execution_mois', sa.Integer(), nullable=True),
    sa.Column('penalite_retard_mille', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('date_parution', sa.Date(), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('date_limite_depot', sa.DateTime(), nullable=True),
    sa.Column('ville_execution', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('agreements_exiges', sa.JSON(), nullable=True),
    sa.Column('seuil_technique_elimination', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tsv_search', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_source_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marches', schema=None) as batch_op:
        batch_op.create_index('idx_marches_tsv', ['tsv_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_budget_estimatif_mad'), ['budget_estimatif_mad'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_limite'), ['date_limite'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_limite_depot'), ['date_limite_depot'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_parution'), ['date_parution'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_montant'), ['montant'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_numero_appel_offre'), ['numero_appel_offre'], unique=True)
        batch_op.create_index(batch_op.f('ix_marches_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_region'), ['region'], unique=False)

    op.create_table('ocr_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=50), nullable=True),
    sa.Column('raw_text_extracted', sa.Text(), nullable=True),
    sa.Column('confidence_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_logs_id'), ['id'], unique=False)

    op.create_table('criteres_humains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('profil_poste', sa.String(length=150), nullable=False),
    sa.Column('points_attribues', sa.Integer(), nullable=True),
    sa.Column('experience_minimale_ans', sa.Integer(), nullable=True),
    sa.Column('inscription_ordre_requise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criteres_humains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteres_humains_id'), ['id'], unique=False)

    op.create_table('ml_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('predicted_categorie', sa.Enum('Travaux', 'Fournitures', 'Services', 'Etudes', name='categoriemarche'), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_insights_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_insights_id'))

    op.drop_table('ml_insights')
    with op.batch_alter_table('criteres_humains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteres_humains_id'))

    op.drop_table('criteres_humains')
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_logs_id'))

    op.drop_table('ocr_logs')
    with op.batch_alter_table('marches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marches_region'))
        batch_op.drop_index(batch_op.f('ix_marches_reference'))
        batch_op.drop_index(batch_op.f('ix_marches_numero_appel_offre'))
        batch_op.drop_index(batch_op.f('ix_marches_montant'))
        batch_op.drop_index(batch_op.f('ix_marches_id'))
        batch_op.drop_index(batch_op.f('ix_marches_date_parution'))
        batch_op.drop_index(batch_op.f('ix_marches_date_limite_depot'))
        batch_op.drop_index(batch_op.f('ix_marches_date_limite'))
        batch_op.drop_index(batch_op.f('ix_marches_budget_estimatif_mad'))
        batch_op.drop_index('idx_marches_tsv')

    op.drop_table('marches')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###
