"""add_document_checksum_sha256

Revision ID: c8e37ca58d02
Revises: 2262aaa7b8c9
Create Date: 2026-07-19 13:20:05.794970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e37ca58d02'
down_revision: Union[str, Sequence[str], None] = '2262aaa7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum_sha256', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_checksum_sha256'), ['checksum_sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_checksum_sha256'))
        batch_op.drop_column('checksum_sha256')

    # ### end Alembic commands ###
