"""Refonte BDD Lot 9

Revision ID: ffeff08a776c
Revises: 
Create Date: 2026-07-19 15:32:51.328280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffeff08a776c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type_agrement', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('agrement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agrement_id'), ['id'], unique=False)

    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_dir', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['direction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direction_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('inferred_type', sa.Enum('Avis', 'CPS', 'RC', 'Engagement', 'Formulaire', 'Inconnu', name='doctype'), nullable=True),
    sa.Column('status', sa.Enum('raw_zip', 'extracted', 'ocr_processed', 'failed', name='docstatus'), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('etat_avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('etat_avis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etat_avis_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('scraper_class', sa.String(length=100), nullable=True),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True),
    sa.Column('selectors_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_id'), ['id'], unique=False)

    op.create_table('type_avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('type_avis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_avis_id'), ['id'], unique=False)

    op.create_table('type_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('type_procedure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_procedure_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ville',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ville', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ville_id'), ['id'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('channels_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_id'), ['id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_id'), ['id'], unique=False)

    op.create_table('extractions_nlp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source_extractor', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extractions_nlp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extractions_nlp_id'), ['id'], unique=False)

    op.create_table('marches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_source_id', sa.Integer(), nullable=True),
    sa.Column('numero_appel_offre', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('titre_projet', sa.Text(), nullable=False),
    sa.Column('organisme_acheteur', sa.String(length=255), nullable=False),
    sa.Column('categorie_prestation', sa.Enum('Travaux', 'Fournitures', 'Services', 'Etudes', name='categoriemarche'), nullable=True),
    sa.Column('typeavis_id', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.Column('etat_id', sa.Integer(), nullable=True),
    sa.Column('date_ouverture_plis', sa.DateTime(), nullable=True),
    sa.Column('langue', sa.String(length=5), nullable=True),
    sa.Column('province_nom', sa.String(length=100), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('modele_reference', sa.String(length=50), nullable=True),
    sa.Column('low_quality', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_estimatif_mad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('caution_provisoire_mad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('caution_definitive_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('delai_execution_mois', sa.Integer(), nullable=True),
    sa.Column('penalite_retard_mille', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('date_parution', sa.Date(), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('date_limite_depot', sa.DateTime(), nullable=True),
    sa.Column('ville_execution', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('agreements_exiges', sa.JSON(), nullable=True),
    sa.Column('seuil_technique_elimination', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tsv_search', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("langue IN ('FR', 'AR', 'BI')", name='chk_langue_enum'),
    sa.CheckConstraint('length(numero_appel_offre) > 0', name='chk_numero_appel_offre_len'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_source_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etat_id'], ['etat_avis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['type_procedure.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['typeavis_id'], ['type_avis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ville_id'], ['ville.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marches', schema=None) as batch_op:
        batch_op.create_index('idx_marches_tsv', ['tsv_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_budget_estimatif_mad'), ['budget_estimatif_mad'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_limite'), ['date_limite'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_limite_depot'), ['date_limite_depot'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_date_parution'), ['date_parution'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_montant'), ['montant'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_numero_appel_offre'), ['numero_appel_offre'], unique=True)
        batch_op.create_index(batch_op.f('ix_marches_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_marches_region'), ['region'], unique=False)

    op.create_table('ocr_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=50), nullable=True),
    sa.Column('raw_text_extracted', sa.Text(), nullable=True),
    sa.Column('confidence_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_processed_page', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_logs_id'), ['id'], unique=False)

    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_search', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_search_id'), ['id'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('alert_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_delivery_id'), ['id'], unique=False)

    op.create_table('criteres_humains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('profil_poste', sa.String(length=150), nullable=False),
    sa.Column('points_attribues', sa.Integer(), nullable=True),
    sa.Column('experience_minimale_ans', sa.Integer(), nullable=True),
    sa.Column('inscription_ordre_requise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criteres_humains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteres_humains_id'), ['id'], unique=False)

    op.create_table('marche_agrement',
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('agrement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agrement_id'], ['agrement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('marche_id', 'agrement_id')
    )
    op.create_table('marche_qualification',
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('marche_id', 'qualification_id')
    )
    op.create_table('ml_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('predicted_categorie', sa.Enum('Travaux', 'Fournitures', 'Services', 'Etudes', name='categoriemarche'), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_insights_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_insights_id'))

    op.drop_table('ml_insights')
    op.drop_table('marche_qualification')
    op.drop_table('marche_agrement')
    with op.batch_alter_table('criteres_humains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteres_humains_id'))

    op.drop_table('criteres_humains')
    with op.batch_alter_table('alert_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_delivery_id'))

    op.drop_table('alert_delivery')
    op.drop_table('user_role')
    with op.batch_alter_table('saved_search', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_search_id'))

    op.drop_table('saved_search')
    op.drop_table('role_permission')
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_logs_id'))

    op.drop_table('ocr_logs')
    with op.batch_alter_table('marches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marches_region'))
        batch_op.drop_index(batch_op.f('ix_marches_reference'))
        batch_op.drop_index(batch_op.f('ix_marches_numero_appel_offre'))
        batch_op.drop_index(batch_op.f('ix_marches_montant'))
        batch_op.drop_index(batch_op.f('ix_marches_id'))
        batch_op.drop_index(batch_op.f('ix_marches_date_parution'))
        batch_op.drop_index(batch_op.f('ix_marches_date_limite_depot'))
        batch_op.drop_index(batch_op.f('ix_marches_date_limite'))
        batch_op.drop_index(batch_op.f('ix_marches_budget_estimatif_mad'))
        batch_op.drop_index('idx_marches_tsv')

    op.drop_table('marches')
    with op.batch_alter_table('extractions_nlp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extractions_nlp_id'))

    op.drop_table('extractions_nlp')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_id'))

    op.drop_table('audit_event')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_id'))

    op.drop_table('alert')
    with op.batch_alter_table('ville', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ville_id'))

    op.drop_table('ville')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('type_procedure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_procedure_id'))

    op.drop_table('type_procedure')
    with op.batch_alter_table('type_avis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_avis_id'))

    op.drop_table('type_avis')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_id'))

    op.drop_table('source')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_id'))

    op.drop_table('qualification')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('etat_avis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etat_avis_id'))

    op.drop_table('etat_avis')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_checksum_sha256'))

    op.drop_table('documents')
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direction_id'))

    op.drop_table('direction')
    with op.batch_alter_table('agrement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agrement_id'))

    op.drop_table('agrement')
    # ### end Alembic commands ###
