import React, { useEffect, useState } from 'react';
import { CheckCircle, Search, Trash2, UserPlus, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import apiClient from '../api/axios';

const emptyForm = { username: '', email: '', password: '', role: 'reader' };
const Users = () => {
  const [users, setUsers] = useState([]); const [term, setTerm] = useState(''); const [form, setForm] = useState(emptyForm); const [showForm, setShowForm] = useState(false);
  const load = async () => { try { setUsers((await apiClient.get('/api/v1/users')).data); } catch (error) { console.error(error); } };
  useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); try { await apiClient.post('/api/v1/users', { username: form.username, email: form.email, password: form.password, roles: [form.role] }); toast.success('Utilisateur créé.'); setForm(emptyForm); setShowForm(false); load(); } catch (error) { console.error(error); } };
  const toggle = async (user) => { try { await apiClient.patch(`/api/v1/users/${user.id}`, { is_active: !user.is_active }); toast.success('Statut mis à jour.'); load(); } catch (error) { console.error(error); } };
  const remove = async (user) => { if (!window.confirm(`Supprimer ${user.username} ?`)) return; try { await apiClient.delete(`/api/v1/users/${user.id}`); toast.success('Utilisateur supprimé.'); load(); } catch (error) { console.error(error); } };
  const filtered = users.filter((user) => `${user.username} ${user.email}`.toLowerCase().includes(term.toLowerCase()));
  return <div className="p-6 max-w-6xl mx-auto space-y-6"><div className="flex justify-between items-center"><h1 className="text-2xl font-bold text-gray-900">Gestion des utilisateurs</h1><button onClick={() => setShowForm(!showForm)} className="bg-blue-600 text-white px-4 py-2 rounded-lg font-medium flex gap-2"><UserPlus size={18} /> Nouvel utilisateur</button></div>{showForm && <form onSubmit={create} className="grid md:grid-cols-4 gap-3 bg-white border p-4 rounded-lg"><input required placeholder="Identifiant" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} className="border rounded p-2"/><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="border rounded p-2"/><input required minLength="8" type="password" placeholder="Mot de passe" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="border rounded p-2"/><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="border rounded p-2"><option value="reader">Lecteur</option><option value="analyst">Analyste</option><option value="admin">Administrateur</option></select><button className="md:col-span-4 bg-zinc-900 text-white rounded p-2">Créer</button></form>}<div className="bg-white border rounded-lg overflow-hidden"><div className="p-4 bg-gray-50"><div className="relative max-w-sm"><Search className="absolute left-3 top-2.5 text-gray-400" size={18}/><input placeholder="Rechercher un utilisateur…" value={term} onChange={(e) => setTerm(e.target.value)} className="w-full border rounded p-2 pl-9"/></div></div><table className="w-full text-left"><thead><tr className="text-xs text-gray-500"><th className="p-4">Utilisateur</th><th>Rôles</th><th>Statut</th><th>Dernière connexion</th><th className="text-right p-4">Actions</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-t"><td className="p-4"><b>{user.username}</b><div className="text-sm text-gray-500">{user.email}</div></td><td>{user.roles.join(', ')}</td><td>{user.is_active ? <span className="text-green-600 flex gap-1"><CheckCircle size={16}/> Actif</span> : <span className="text-red-600 flex gap-1"><XCircle size={16}/> Inactif</span>}</td><td>{user.last_login_at ? new Date(user.last_login_at).toLocaleString('fr-FR') : 'Jamais'}</td><td className="p-4 text-right"><button onClick={() => toggle(user)} className="mr-3 text-blue-600">{user.is_active ? 'Désactiver' : 'Activer'}</button><button onClick={() => remove(user)} className="text-red-600" aria-label={`Supprimer ${user.username}`}><Trash2 size={18}/></button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-gray-500">Aucun utilisateur trouvé.</p>}</div></div>;
};
export default Users;
